#
# VerboseStartup: toggle that determines if configuration values are printed at
#                     plugin startup
#
# Allowed values are: Yes 
#                     No
# 
VerboseStartup: No

#
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values are: Yes 
#                     No 
# 
ShowErrorsInClient: Yes

#
# AllowNonOpAccess: if there is no permissions plugin loaded, then this setting 
#                   allows users without op status to access signs
#
# Allowed values are: Yes
#                     No
#
AllowNonOpAccess: No

#
# SignTag: the text that must be placed between brackets on the first line of a
#          replicator sign  
#
# Allowed value: any single word, ie. "Replicator", "GetStuff", "Toast"
#
SignTag: Replicator
